config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "events#top"
  get "/contact",   to: "static_page#contact"
  post "/contact",  to: "static_page#contact_for_admin"
  
  #特定商取引法に基づく表記
  get "/tokushohyo",  to: "static_page#tokushohyo"
  get "/term",        to: "static_page#term"
  get "/privacy",     to: "static_page#privacy"
  get "/howtouse",     to: "static_page#howtouse"
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
#    :confirmations => 'users/confirmations'
  }
  
#   ユーザー管理関連
  resources :users, only: [:show]

  
# イベント管理関連  
  get "events/confirm", to: "events#confirm"
  resources :events do
    resources :reserves,     only: [:create]
    post "/create_with_resistration", to: "reserves#createWithResistration" 
  end
  resources :reserves,       only: [:destroy]
  get "reserves/:id/cancel", to: "reserves#cancel"
  get "user/reserved",       to: "reserves#reserved"
  
  
# ユーザー情報関連
  get "user/profile",       to: "users#profile"
  get "user/edit",          to: "users#edit"
  patch "user/update",      to: "users#update"
  patch "user/update_pass", to: "users#updatePass"
  post "passwords",         to: "users#resetPass"

# 支払い関連
  resources :pays, only: [:new, :create]
  get "user/pays/confirm_card",           to: "pays#confirmCard"
  get "user/pays/edit_card",              to: "pays#editCard"
  post "user/pays/update_card",           to: "pays#updateCard"
  get "user/pays/confirm",                to: "pays#confirm"
  get "user/pays/hostnew",                to: "pays#hostNew"
  post "user/pays/host"  ,                to: "pays#hostCreate"
  get "user/pays/hostinfo" ,              to: "pays#hostInfo"
  get "user/pays/hostedit",               to: "pays#hostEdit"
  post "user/pays/hostupdate",            to: "pays#hostUpdate"
  get "pays/new_withoutresistration",     to: "pays#newWithoutResistration"
  post "pays/create_withoutresistration", to: "pays#createWithoutResistration"
  get "user/pays/profit",                 to: "pays#profit"
end

app/views/shared/_done_loading.js.erb
$(function(){
  doneLoading();
});

app/views/shared/_error_notice.html.erb
<% if model.errors.any? %>
  <div class="pink-btn error-notice">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="flash-notice">
  <p><%= flash[:notice] %></p>
</div>

<script>
$(function(){
  setTimeout(function(){
    $(".flash-notice").remove();  
  }, 3000);
});  
</script>
<% end %>

app/views/shared/_sidebar_organizer.html.erb
<div class="sidebar">
  <h3><i class="fa fa-bars" aria-hidden="true"></i> MENU</h3>
  <div class="sidebar-box">
    <h4 class="sidebar-subtitle btn-hover"><span class="sidebar-icon"><i class="fa fa-home" aria-hidden="true"></i> マイページ</span><span><i class="fa fa-angle-double-right" aria-hidden="true"></i></span></h4>
    <ul style="display:none;">
      <li><%= link_to "ホーム", user_profile_path %></li>
    </ul>
  </div>
  
  <div class="sidebar-box">
    <h4 class="sidebar-subtitle btn-hover"><span class="sidebar-icon"><i class="fa fa-thumb-tack" aria-hidden="true"></i> イベント参加管理</span><span><i class="fa fa-angle-double-right" aria-hidden="true"></i></span></h4>
    <ul style="display:none;">
      <li><%= link_to "予約したイベントの確認", user_reserved_path(future:true, past:true) %></li>
    </ul>
  </div>
  
  <div class="sidebar-box">
    <h4 class="sidebar-subtitle btn-hover"><span class="sidebar-icon"><i class="fa fa-thumb-tack" aria-hidden="true"></i> イベントホスト管理</span><span><i class="fa fa-angle-double-right" aria-hidden="true"></i></span></h4>
    <ul style="display:none;">
        <li><%= link_to "イベント新規登録", new_event_path %></li>
        <li><%= link_to "登録したイベントの確認", events_confirm_path %></li>
    </ul>    
  </div>
  
  <div class="sidebar-box">
    <h4 class="sidebar-subtitle btn-hover"><span class="sidebar-icon"><i class="fa fa-credit-card" aria-hidden="true"></i> お支払い</span><span><i class="fa fa-angle-double-right" aria-hidden="true"></i></span></h4>
    <ul style="display:none;">
      <li><%= link_to "カード登録", new_pay_path, data: {"turbolinks" => false} %></li>
      <li><%= link_to "カード確認・変更", user_pays_confirm_card_path %></li>
    </ul>
  </div>
  
  <div class="sidebar-box">
    <h4 class="sidebar-subtitle btn-hover"><span class="sidebar-icon"><i class="fa fa-database" aria-hidden="true"></i> 売上管理</span><span><i class="fa fa-angle-double-right" aria-hidden="true"></i></span></h4>
    <ul style="display:none;">
      <li><%= link_to "振込口座登録", user_pays_hostnew_path %></li>
      <li><%= link_to "振込口座確認・編集", user_pays_hostinfo_path %></li>
      <li><%= link_to "売り上げ管理", user_pays_profit_path %></li>
    </ul>
  </div>  
  
  <div class="sidebar-box">
    <h4 class="sidebar-subtitle btn-hover"><span class="sidebar-icon"><i class="fa fa-user" aria-hidden="true"></i> 登録情報管理</span><span><i class="fa fa-angle-double-right" aria-hidden="true"></i></span></h4>    
    <ul style="display:none;">
      <li><%= link_to "ユーザー情報", user_edit_path %></li>
      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>  

</div>



<script>
$(function(){
  $(".sidebar-subtitle").on("click", function(){
    $(this).next("ul").css("display", "");
    
    
    
  });  
});
</script>

app/views/shared/_start_loading.js.erb
$(function(){
  stateLoading();
}); 

app/views/shared/errorDetail.js.erb
$(function(){
  <% if @user.present? %>
  $("#error-notice").html("<%= j(render 'shared/error_notice', { model: @user }) %>");
  <% end %>
});