config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "events#top"
  get "/contact",   to: "static_page#contact"
  post "/contact",  to: "static_page#contact_for_admin"
  
  #特定商取引法に基づく表記
  get "/tokushohyo",  to: "static_page#tokushohyo"
  get "/term",        to: "static_page#term"
  get "/privacy",     to: "static_page#privacy"
  get "/howtouse",     to: "static_page#howtouse"
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
#    :confirmations => 'users/confirmations'
  }
  
#   ユーザー管理関連
  resources :users, only: [:show]

  
# イベント管理関連  
  get "events/confirm", to: "events#confirm"
  resources :events do
    resources :reserves,     only: [:create]
    post "/create_with_resistration", to: "reserves#createWithResistration" 
  end
  resources :reserves,       only: [:destroy]
  get "reserves/:id/cancel", to: "reserves#cancel"
  get "user/reserved",       to: "reserves#reserved"
  
  
# ユーザー情報関連
  get "user/profile",       to: "users#profile"
  get "user/edit",          to: "users#edit"
  patch "user/update",      to: "users#update"
  patch "user/update_pass", to: "users#updatePass"
  post "passwords",         to: "users#resetPass"

# 支払い関連
  resources :pays, only: [:new, :create]
  get "user/pays/confirm_card",           to: "pays#confirmCard"
  get "user/pays/edit_card",              to: "pays#editCard"
  post "user/pays/update_card",           to: "pays#updateCard"
  get "user/pays/confirm",                to: "pays#confirm"
  get "user/pays/hostnew",                to: "pays#hostNew"
  post "user/pays/host"  ,                to: "pays#hostCreate"
  get "user/pays/hostinfo" ,              to: "pays#hostInfo"
  get "user/pays/hostedit",               to: "pays#hostEdit"
  post "user/pays/hostupdate",            to: "pays#hostUpdate"
  get "pays/new_withoutresistration",     to: "pays#newWithoutResistration"
  post "pays/create_withoutresistration", to: "pays#createWithoutResistration"
  get "user/pays/profit",                 to: "pays#profit"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :reserves
  
  # 入力フォームのバリデーション
  validates :title, presence: true
  validates :start_date, presence: true
  validates :start_time, presence: true
  validates :venue, presence: true
  validates :venue_pass, presence: true
  validates :venue_method, presence: true
  validates :content, presence: true
  validates :price, presence: true
  validates :capacity, presence: true
  validates :imgs, presence: true
  
  # active storage 使用
  has_many_attached :imgs
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :confirm]
  before_action :user_info, only: [:new, :create, :confirm] 
  before_action :tenant_resistration, only: [:new, :create]
  after_action :store_location
  # before_action :move_to_index, except: [:index,:show ]
  # indexアクション以外が実行される前にindexが実行される。
  require 'base64'
    
  # トップ画面、イベント検索  
  def top
    @events = Event.includes(:user).order("start_date ASC")
    not_expired_event
    @events = @events.order("start_date ASC")
    if params[:venue_method].present?
      @events = @events.where(venue_method: params[:venue_method])
    end
    if params[:date].present?
      @events = @events.where(start_date: params[:date].in_time_zone.all_day)
    end
    if params[:max].present? && params[:min].present?
      @events = @events.where(price: params[:min] .. params[:max])
    elsif params[:max].present?
      @events = @events.where(price: Float::MIN .. params[:max].to_i)
    elsif params[:min].present?
      @events = @events.where(price: params[:min].to_i .. Float::INFINITY)
    end
    if params[:keyword].present?
      @events = @events.where("title LIKE ?", "%#{params[:keyword]}%")
    end
    @events = @events.page(params[:page]).per(10)
  end

  # イベントの新規登録画面
  def new
    @event = Event.new
  end
  
  # イベントの新規登録
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    @event_datetime = to_date_and_time(@event.start_date, @event.start_time)
    @event_price = @event.price
    
    if @event_datetime < Time.zone.now
      render "inputTimeError.js.erb"
    elsif  @event_price < 100
      render "inputPriceError.js.erb"  
    else  
      if @event.save
        EventMailer.mail_event_create(@event).deliver_now
        flash[:notice] = "イベントの登録が完了しました！"
        redirect_to events_confirm_path
      else
        render "inputError.js.erb"
      end
    end
  end
  
  # イベントの編集画面
  def edit
    @event = Event.find(params[:id])
  end
  
  # イベント情報の更新
  def update
    @event = Event.find(params[:id])
    @deleteImgs = params[:event][:deleteImg]
    @imgs = @deleteImgs[0].split(',')
    
    if @imgs.size == @event.imgs.size
        flash[:notice] = "画像は必ず登録してください。"
        redirect_to session[:privious_url]
    else
      @newDate = params[:event][:start_date]
      @event_datetime = to_date_and_time_three(@newDate.to_datetime, params[:event][:"start_time(4i)"], params[:event][:"start_time(5i)"])
      @event_price = params[:event][:price].to_i
      
      if @event_datetime < Time.zone.now
        render "inputTimeError.js.erb"
      elsif @event_price < 100
        render "inputPriceError.js.erb"  
      else  
        if @event.update(event_params)
          @imgs.each do |i|
            @index = i.to_i
            @event.imgs[@index].purge
          end
          flash[:notice] = "イベントの情報が更新されました！"
          redirect_to events_confirm_path  
        else
          render "inputError.js.erb"
        end
      end
    end
  end
  
  
  def confirm
    @events = Event.where(user_id: @user.id).page(params[:page]).per(5)
    if user_signed_in?
      @card = Card.find_by(user_id: current_user.id)
    end
  end

  # イベント詳細表示
  def show
    @event = Event.includes(:user).find(params[:id])
    @reserves = Reserve.where(event_id: params[:id])
    
    @reserve = Reserve.new
    @user = User.new
  end
  
  # イベントの削除
  def destroy
    @event = Event.find(params[:id])
    @reserves = Reserve.where(event_id: @event.id) 
    if @event.user_id == current_user.id
      reserves_cancel
      @event.destroy
      EventMailer.mail_event_destroy(@event).deliver_now
      flash[:notice] = "イベントをキャンセルしました。"
      redirect_to events_confirm_path
    else
      flash[:notice] = "イベントをキャンセルできませんでした。"
      redirect_to events_confirm_path
    end
  end
  
    private
      def event_params
        params.require(:event).permit(:title, :start_date, :start_time, :venue_method, :venue, :venue_pass, :price, :content, :capacity, imgs: [])
      end
      
      def move_to_index
       redirect_to action: :index unless user_signed_in?
      end
      
      # テナント登録してない場合、新規イベント登録不可
      def tenant_resistration 
        @tenant = Tenant.find_by(user_id: current_user.id)
        unless @tenant.present?
          flash[:notice] = "イベント登録前に銀行口座登録を行ってください"
          redirect_to user_pays_hostnew_path
        end
      end
      
      # イベントの予約をすべてキャンセル
      def reserves_cancel
        @reserves.each do |reserve|
          @reserve = reserve  
          # 支払い済みの場合
          if @reserve.payed
            payjp_cancel_action
          end
          if @reserve.destroy
            ReserveMailer.mail_event_destroy_for_user(@reserve).deliver_now
            ReserveMailer.mail_cancel_complite(@reserve).deliver_now
          else
            flash[:notice] = "イベントのキャンセルに失敗しました。"
            redirect_to session[:privious_url]
          end
        end
      end
      
      # 支払い情報の保存
      def pay_db_resister
        @pay_new = Pay.new(host_id: @event.user_id, price: - @event.price, 
                       card_id: @pay.id, reserve_id: @reserve.id, charge_id: @pay.charge_id)
        @pay_new.user_id = current_user.id if user_signed_in?
        @pay_new.save
      end
      
      # payjpキャンセルアクション
      def payjp_cancel_action
        begin
          Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
          @pay = Pay.find_by(reserve_id: @reserve.id)
          charge = Payjp::Charge.retrieve(@pay.charge_id)
          charge.refund
          pay_db_resister
          @reserve.update(payed: false)
        rescue Payjp::CardError => e
          flash[:notice] = 'カード情報の取得ができませんでした。'
          render "payError.js"
        rescue Payjp::InvalidRequestError => e
          flash[:notice] = '不正なパラメータが入力されました。'
          render "payError.js"
        rescue Payjp::AuthenticationError => e
          flash[:notice] = 'カード情報の取得ができませんでした。'
          render "payError.js"
        rescue Payjp::APIConnectionError => e
          flash[:notice] = '通信エラーが発生しました。'
          render "payError.js"
        rescue Payjp::APIError => e
          flash[:notice] = '通信エラーが発生しました。'
          render "payError.js"
        rescue Payjp::PayjpError => e
          flash[:notice] = 'カード情報の取得ができませんでした。'
          render "payError.js"
        rescue StandardError
          flash[:notice] = 'エラーが発生しました。'
          render "payError.js"
        end
      end
      
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_resistration.html.erb
<!--参加予約-->

<script>
$(function(){
  var attendForm = `
    <div id="event-attend-form">
    <div class="event-attend-form">
      <div class="event-attend__content">
      <div class="event-attend__top">
        <h3><i class="fa fa-thumb-tack" aria-hidden="true"></i> イベントの予約</h3>
        <p class="btn-hover" id="event-attend-form-close">&times;</p>
      </div>
      
      <% if user_signed_in? %>
      <div id="error-notice"></div>
      <div class="event-attend__detail">
        <h4><i class="fa fa-user" aria-hidden="true"></i> 参加者情報</h4>
        <div class="event-attend__detail-info">
          <table>
            <tr>
              <th>名前</th>
              <td><%= current_user.nickname %></td>
            </tr>
            <tr>
              <th>E-mail</th>
              <td><%= current_user.email %></td>
            </tr>
          </table>
        </div>
      </div>
      <% end %>
      
      <div class="event-attend__detail">
        <h4><i class="fa fa-info-circle" aria-hidden="true"></i> イベント詳細</h4>
        <div class="event-attend__detail-info">
          <table>
            <tr>
              <th>イベント名</th>
              <td><%= @event.title %></td>
            </tr>
            <tr>
              <th>開催日時</th>
              <td><%= @event.start_date.strftime("%-m月%-d日") %><%= day_of_the_week(@event.start_date.strftime("%u")) %> <%= @event.start_time.strftime("%H:%M") %>～</td>
            </tr>
            <tr>
              <th>参加費</th>
              <td><%= @event.price.to_s(:delimited) %> 円</td>
            </tr>
            <tr>
              <th>定員</th>
              <td><%= @event.capacity %> 名</td>
            </tr>
            <tr>
              <th>ホスト</th>
              <td><%= @event.user.nickname %></td>
            </tr>
          </table>
          <div id="error-notice"></div>
        </div>
        <% if user_signed_in? %>
        <div class="event-attend__submit-box">
          <p><%= link_to "利用規約", term_path %>、<%= link_to "プライバシーポリシー", privacy_path %>に同意の上 </p>
          <% if @card.present? %>
          <%= button_to "予約する", event_reserves_path(@event.id), remote: true, class:"submit-btn orange-btn btn-hover", title: "イベント予約・支払い", data: {confirm: "イベントの予約、登録されたクレジットカードによる支払いを行ってよろしいでしょうか？", cancel: "やめる", commit: "確定"} %>
          <% else %>
          <%= button_to "予約する", event_reserves_path(@event.id), remote: true, class:"submit-btn orange-btn btn-hover", title: "イベント予約", data: {confirm: "イベントの予約を行ってよろしいでしょうか？", cancel: "やめる", commit: "確定"} %>
          <% end %>
        </div>
        <% else %>
        <div class="event-attend__select">
          <input type="checkbox" id="select-registration"></input>
          <label for="select-registration">ユーザー登録も一緒に行う</label>
          <p>（アカウントをお持ちの方 <%= link_to "ログイン", user_session_path %>）</p>
        </div>
        <div class="event-attend__form" id="event-attend__form-without">
        <%= form_with(model: @reserve, url: event_reserves_path(@event.id)) do |f| %>
          <div class="event-attend__form-box">
            <p><i class="fa fa-user-o" aria-hidden="true"></i></p>
            <%= f.text_field:nickname, placeholder: "名前" %>
          </div>
          <div class="event-attend__form-box">
            <p><i class="fa fa-envelope-o" aria-hidden="true"></i></p>
            <%= f.email_field:email, placeholder: "E-mail" %>
          </div>
          <div class="event-attend__submit-box">
            <p><%= link_to "利用規約", term_path %>、<%= link_to "プライバシーポリシー", privacy_path %>に同意の上 </p>
            <%= f.submit "予約する", class:"submit-btn orange-btn btn-hover", title: "イベント予約", data: {confirm: "イベントの予約を行ってよろしいでしょうか？", cancel: "やめる", commit: "確定"} %>
          </div>
        <% end %>
        </div>
        <% end %>
      </div>
    </div>
    </div>
    </div>`
  
  // ユーザー登録込みのフォーム  
  var formWithResistration = `
    <div class="event-attend__form" id="event-attend__form-with">
    <%= form_with(model: @user, url: event_create_with_resistration_path(@event.id)) do |f| %>
      <div class="event-attend__form-box">
        <p><i class="fa fa-user-o" aria-hidden="true"></i></p>
        <%= f.text_field:nickname, placeholder: "名前" %>
      </div>
      <div class="event-attend__form-box">
        <p><i class="fa fa-envelope-o" aria-hidden="true"></i></p>
        <%= f.text_field:email, placeholder:"E-mail" %>
      </div>
      <div class="event-attend__form-box">
        <p><i class="fa fa-lock" aria-hidden="true"></i></p>
        <%= f.password_field :password, autocomplete: "new-password", placeholder: "パスワード" %>
      </div>
      <div class="event-attend__form-box">
        <p><i class="fa fa-lock" aria-hidden="true"></i></p>
        <%= f.password_field :password_confirmation, autocomplete: "new-password", placeholder: "パスワード（確認）" %>
      </div>
      <div class="event-attend__submit-box">
        <p><%= link_to "利用規約", term_path %>、<%= link_to "プライバシーポリシー", privacy_path %>に同意の上 </p>
        <%= f.submit "予約・ユーザー登録する", class:"submit-btn orange-btn btn-hover", title: "イベント予約・新規ユーザー登録", data: {confirm: "イベントの予約および新規ユーザー登録を行ってよろしいでしょうか？", cancel: "やめる", commit: "確定"}  %>
      </div>
    <% end %>
    </div>`  
  
  // ユーザー登録なしのフォーム
  var formWithoutResistration = `
    <div class="event-attend__form" id="event-attend__form-without">
    <%= form_with(model: @reserve, url: event_reserves_path(@event.id)) do |f| %>
      <div class="event-attend__form-box">
        <p><i class="fa fa-user-o" aria-hidden="true"></i></p>
        <%= f.text_field:nickname, placeholder: "名前" %>
      </div>
      <div class="event-attend__form-box">
        <p><i class="fa fa-envelope-o" aria-hidden="true"></i></p>
        <%= f.email_field:email, placeholder: "E-mail" %>
      </div>
      <div class="event-attend__submit-box">
        <p><%= link_to "利用規約", term_path %>、<%= link_to "プライバシーポリシー", privacy_path %>に同意の上 </p>
        <%= f.submit "予約する", class:"submit-btn orange-btn btn-hover", title: "イベント予約", data: {confirm: "イベントの予約を行ってよろしいでしょうか？", cancel: "やめる", commit: "確定"} %>
      </div>
    <% end %>
    </div>`

  $("#event-attend").on("click", function(){
    $.when(
      $("#display").animate({opacity: .8}, 300)
    ).done(function(){
      $("#event-attend").after(attendForm);
      $("#display").css("display", "");
      
      // closeボタンを押したとき
      $("#event-attend-form-close").on("click", function(){
        $.when(
          $("#display").animate({opacity: 0}, 300),
          $("#event-attend-form").animate({opacity: 0}, 300)
        ).done(function(){
          $("#event-attend-form").remove();
          $("#display").css("display", "none");
        }); 
      });
      
      // チェックボックスのクリックをしたとき
      $("#select-registration").on("change", function(){
        var flag = $("#select-registration").prop("checked");

        if (flag){
          var countWithRegistration = $("#event-attend__form-with").length;
          if(countWithRegistration == 0){
            $("#event-attend__form-without").remove();
            $(".event-attend__detail").append(formWithResistration);
          }
        }else{
          var countWithoutRegistration = $("#event-attend__form-without").length;
          if(countWithoutRegistration == 0){
            $("#event-attend__form-with").remove();
            $(".event-attend__detail").append(formWithoutResistration);
          }
        }
      });
      
    });
  });
});  
</script>

app/views/events/inputError.js.erb
$(function(){
  <% if @event.present? %>
  $("#error-notice").html("<%= j(render 'shared/error_notice', { model: @event }) %>");
  <% end %>
});

app/views/events/inputPriceError.js.erb
$(function(){
  var noticeCount = $(".start_datetime_error").length;
  if(noticeCount == 0){
    console.log(noticeCount);
    $("#error-notice").html('<div class="pink-btn error-notice"><ul><li>参加費は１００円以上に設定してください</li></ul></div>');  
  }
});

app/views/events/new.html.erb
<% provide(:title, "イベント作成") %>

<%= render "shared/flash" %>
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-3">
      <%= render "shared/sidebar_organizer" %>
    </div>  
  
    <div class='col-12 col-sm-9 content'>
      <div class="page-title">
        <h1>イベント作成</h1>
      </div>
      
      <div class="event">
        <div id="error-notice"></div>
        <%= form_with(model: @event, url: events_path, method: :post) do |f| %>
          <div class="event-form">
            <label for="event_title">イベント名<br><span class="pink-btn form-necessary">必須</span></label>
            <%= f.text_field:title, class:"form-control form-control-lg" %>
          </div>
          <div class="event-form event-form-date">
            <label for="event_start_date">開催日時<br><span class="pink-btn form-necessary">必須</span></label>
            <%= f.date_field:start_date, class:"form-control" %>
            <%= f.time_select:start_time, {}, class:"form-control", ignore_data:true %>
          </div>
          <div class="event-form">
            <label for="event_content">イベント内容<br><span class="pink-btn form-necessary">必須</span></label>
            <%= f.text_area:content, class:"form-control form-control-lg event-form-content", placeholder: "開催するイベントの内容を書いてください" %>
          </div>
          <div class="event-form" id="event-method">
            <label>開催形式<br><span class="pink-btn form-necessary">必須</span></label>
            <%= f.hidden_field:venue_method, value: "online", id: "venue-method" %>
            <ul>
              <li class="orange-btn btn-hover" id="event-method-online" onclick="">オンライン</li>
              <li class="unselect-btn btn-hover" id="event-method-offline" onclick="">オフライン</li>
            </ul>
          </div>
          <div class="event-form event-form-online">
            <label for="event_venue">Zoom ID<br><span class="pink-btn form-necessary">必須</span></label>
            <%= f.text_field:venue, class:"form-control form-control-lg" %>
          </div>
          <div class="event-form event-form-online">
            <label for="event_venue_pass">Zoom Password<br><span class="pink-btn form-necessary">必須</span></label>
            <%= f.text_field:venue_pass, class:"form-control form-control-lg" %>
          </div>
          <div class="event-form">
            <label for="event_capacity">定員<br><span class="pink-btn form-necessary">必須</span></label>
            <%= f.number_field:capacity, class:"form-control form-control-lg" %>
          </div>
          <div class="event-form">
            <label for="event_price">参加費<br><span class="pink-btn form-necessary">必須</span></label>
            <%= f.number_field:price, class:"form-control form-control-lg" %>
          </div>
          <div class="event-form">
            <label for="event_imgs">画像<br><span class="pink-btn form-necessary">必須</span></label>
            <label class="event-form__img-field" for="img-file" id="event-form__img-label-new"><span class="submit-btn orange-border-btn"><i class="fa fa-image" aria-hidden="true"></i> 画像をアップロード</span></label>
            <%= f.file_field:imgs, multiple: true, class:"event-form__img-file event-form__img-file-new", id:"img-file", style:"display: none;" %>
          </div>
          <div id="event-form__img"></div>
          <div class="event-submit">
            <p><%= link_to "利用規約", term_path, style:"font-weight: bold;" %>、<%= link_to "プライバシーポリシー", privacy_path, style:"font-weight: bold;" %>に同意の上 </p>
            <%= f.submit "イベント作成", class:"submit-btn orange-btn btn-hover" %>
          </div>
        <% end %>
      </div>
    </div>
    
  </div>
</div>


<script>
$(function(){
    var userAgent = window.navigator.userAgent.toLowerCase();
    if (userAgent.indexOf('safari') != -1){
      $("#event-form__img-label-new").css("display", "none");
      $(".event-form__img-file-new").css("display", "");
    }
});  
</script>
<script>
$(function(){
  // オンライン・オフラインスイッチング
  var online = `
    <div class="event-form event-form-online">
      <label for="event_venue">Zoom ID<br><span class="pink-btn form-necessary">必須</span></label>
      <input class="form-control form-control-lg" type="text" name="event[venue]" id="event_venue">
    </div>
    <div class="event-form event-form-online">
      <label for="event_venue_pass">Zoom Password<br><span class="pink-btn form-necessary">必須</span></label>
      <input class="form-control form-control-lg" type="text" name="event[venue_pass]" id="event_venue_pass">
    </div>`
    
  var offline = `
    <div class="event-form event-form-offline">
      <label for="event_venue">開催場所<br><span class="pink-btn form-necessary">必須</span></label>
      <input class="form-control form-control-lg" type="text" name="event[venue]" id="event_venue">
      <input class="form-control form-control-lg" type="hidden" value="none" name="event[venue_pass]" id="event_venue_pass">
    </div>`
    
  $("#event-method-online").on("click", function(){
    var count = $(".event-form-online").length;
    if(count == 0){
      $(this).removeClass("unselect-btn");  
      $(this).addClass("orange-btn");
      $("#event-method-offline").addClass("unselect-btn");
      $("#event-method-offline").removeClass("orange-btn");
      $(".event-form-offline").remove();
      $("#event-method").after(online);
      $("#venue-method").val("online");
    } 

  });
  
  $("#event-method-offline").on("click", function(){
    var count = $(".event-form-offline").length;
    if(count == 0){
      $(this).removeClass("unselect-btn");  
      $(this).addClass("orange-btn");
      $("#event-method-online").addClass("unselect-btn");
      $("#event-method-online").removeClass("orange-btn");
      $(".event-form-online").remove();
      $("#event-method").after(offline);
      $("#venue-method").val("offline");
    } 

  });
});  
</script>
<script>
$(function(){
  var dataBox = new DataTransfer();
  var file_field = document.querySelector('input[type=file]');
  
  $('#img-file').on("change", function(){
    var files = $('input[type="file"]').prop('files')[0];
    $.each(this.files, function(i, file){
      var fileReader = new FileReader();
      dataBox.items.add(file);
      
      file_field.files = dataBox.files;
      var num = $('.item-image').length + 1 + i;
      fileReader.readAsDataURL(file);

      if (num == 7){
        $('#image-box__container').css('display', 'none');   
      }
  
      fileReader.onloadend = function() {
        var src = fileReader.result;
        var imgBox= 
          `<div class="event-form__img-wrap item-image" data-image="${file.name}">
            <div class="event-form__img-box">
              <img src=${src} class="event-form__img">
            </div>
            <div class="event-form__img-remove" onclick="">
              <p><i class="fa fa-remove btn-hover" aria-hidden="true"></i></p>
            </div>
          </div>`
          
        $('#event-form__img').append(imgBox);
      }
      $('#image-box__container').attr('class', `item-num-${num}`);
    })
  });
  
  // //削除関連
  $(document).on("click", '.event-form__img-remove', function(){
    var target_image = $(this).parent();
    var target_name = $(target_image).data('image');
    
    if(file_field.files.length == 1){
      $("input[type=file]").val(null);
      dataBox.clearData();
    }else{
      
      $.each(file_field.files, function(i,input){
        if(input.name == target_name){
          dataBox.items.remove(i);
        }
      });
      file_field.files = dataBox.files;
    }
    target_image.remove();
    var num = $('.item-image').length;
    $('#image-box__container').show();
    $('#image-box__container').attr('class', `item-num-${num}`);
  });
  
});
</script>

app/views/events/top.html.erb
<!--top画像表示-->
<%= render "shared/flash" %>
<div class="top">
  <div class="top-img">
    <%= image_tag "top.jpg" %>
  </div>
  <!--検索バー-->
  <%= render "events/search_event" %>
</div>



<div class="container">
  <div class="">
    <!--各イベント表示-->
    <div class="event-top">
      <div class="page-title">
        <h1>お探しのイベントは？</h1>
      </div>
      
      <% if @events.size == 0 %>
      <% if params[:commit].present? %>
      <div class="event-top__result event-top__result-zero">
        <p>検索条件にマッチするイベントは、現在のところ予定されておりません。</p>
      </div>
      <% else %>
      <div class="event-top__result event-top__result-zero">
        <p>現在登録されているイベントはありません。</p>
      </div>
      <% end %>
      <% else %>
      <% if params[:commit].present? %>
      <div class="event-top__result event-top__result-not-zero">
        <p>条件にマッチしたイベントが見つかりました！</p>
      </div>
      <% end %>
      <% end %>
      
      
      
      <% @events.each do |event| %>
      <div class="event-top__box box-wrap">
        <div class="event-top__header" style="width: 100%;">
          <p class="pink-btn">募集中</p>
          <% if event.venue_method == "online" %>
          <p class="orange-btn">オンライン</p>
          <% elsif event.venue_method == "offline" %>
          <p class="blue-btn">オフライン</p>
          <% end %>
        </div>
        <div class="event-top__img">
          <% event.imgs.each do |img| %>
            <%= image_tag img, class:"event-img wide-img-hover" %>
          <% end %>
          <% if event.imgs.empty? %>
            <%= image_tag "NoImage.png", class:"event-img" %>
          <% end %>
        </div>
        <div class="event-top__detail">
          <h2><%= event.title %></h2>
          <table>
            <tr>
              <th><i class="fa fa-clock-o" aria-hidden="true"></i> 開催日時</th>
              <td><%= event.start_date.strftime("%-m月%-d日") %><%= day_of_the_week(event.start_date.strftime("%u")) %> <%= event.start_time.strftime("%H:%M") %>～</td>
            </tr>
            <tr>
              <th><i class="fa fa-bookmark-o" aria-hidden="true"></i> 参加費</th>
              <td><%= event.price.to_s(:delimited) %> 円</td>
            </tr>
            <tr>
              <th><i class="fa fa-bookmark-o" aria-hidden="true"></i> ホスト</th>
              <td><span class="link host-info-<%= event.id %>"><%= event.user.nickname %></span></td>
            </tr>
          </table>
          <div class="event-box__hostinfo-box" id="event-box__hostinfo-box-<%= event.id %>" style="display: none;"></div>
        </div>
        
        <div class="event-top__btn">
          <p class=""><%= link_to "詳細をみる", event_path(event.id), class:"wide-submit-btn btn-hover orange-btn" %></p>
        </div>
        <% @event = event %>
        <%= render "events/hostname", collection: @event %>
      </div>
      <% end %>
      <%= paginate(@events) %>
    </div>
  </div>
</div>



<script>
$(function() {
  $(".event-top__img").slick({
    dots: true
  });
});  
</script>