config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "events#top"
  get "/contact",   to: "static_page#contact"
  post "/contact",  to: "static_page#contact_for_admin"
  
  #特定商取引法に基づく表記
  get "/tokushohyo",  to: "static_page#tokushohyo"
  get "/term",        to: "static_page#term"
  get "/privacy",     to: "static_page#privacy"
  get "/howtouse",     to: "static_page#howtouse"
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
#    :confirmations => 'users/confirmations'
  }
  
#   ユーザー管理関連
  resources :users, only: [:show]

  
# イベント管理関連  
  get "events/confirm", to: "events#confirm"
  resources :events do
    resources :reserves,     only: [:create]
    post "/create_with_resistration", to: "reserves#createWithResistration" 
  end
  resources :reserves,       only: [:destroy]
  get "reserves/:id/cancel", to: "reserves#cancel"
  get "user/reserved",       to: "reserves#reserved"
  
  
# ユーザー情報関連
  get "user/profile",       to: "users#profile"
  get "user/edit",          to: "users#edit"
  patch "user/update",      to: "users#update"
  patch "user/update_pass", to: "users#updatePass"
  post "passwords",         to: "users#resetPass"

# 支払い関連
  resources :pays, only: [:new, :create]
  get "user/pays/confirm_card",           to: "pays#confirmCard"
  get "user/pays/edit_card",              to: "pays#editCard"
  post "user/pays/update_card",           to: "pays#updateCard"
  get "user/pays/confirm",                to: "pays#confirm"
  get "user/pays/hostnew",                to: "pays#hostNew"
  post "user/pays/host"  ,                to: "pays#hostCreate"
  get "user/pays/hostinfo" ,              to: "pays#hostInfo"
  get "user/pays/hostedit",               to: "pays#hostEdit"
  post "user/pays/hostupdate",            to: "pays#hostUpdate"
  get "pays/new_withoutresistration",     to: "pays#newWithoutResistration"
  post "pays/create_withoutresistration", to: "pays#createWithoutResistration"
  get "user/pays/profit",                 to: "pays#profit"
end

app/models/pay.rb
class Pay < ApplicationRecord
    
    belongs_to :card
    belongs_to :reserve
    
end

app/controllers/pays_controller.rb
class PaysController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :confirmCard, :editCard, :updateCard, :profit, 
                                            :hostNew, :hostCreate, :hostInfo, :hostEdit, :hostUpdate]
  before_action :user_info, only: [:new, :create, :confirmCard, :editCard, :updateCard, :profit, 
                                   :hostNew, :hostCreate, :hostInfo, :hostEdit, :hostUpdate]
  before_action :store_location, only: [:newWithoutResistration, :new, :confirmCard, :editCard, :profit, :hostNew, :hostEdit, :hostInfo]
  before_action :register_bank_account, only: [:profit]
  
  # http通信実装のためのライブラリ
  require 'net/https'
  require 'uri'
  
  # payjp API用
  require 'payjp'
  
  # カード登録がない状態で支払いを行う表示
  def newWithoutResistration
    if params[:reserve_id].present?
      @reserve = Reserve.find(params[:reserve_id])
      @event = Event.find(@reserve.event_id)
    end
    @pay = Pay.new
  end
  
  # カード登録がない状態で支払い
  def createWithoutResistration
    @reserve = Reserve.find(params[:reserve_id])
    @event = Event.find(@reserve.event_id)
    @tenant = Tenant.find_by(user_id: @event.user_id)
    
    if params["payjp-token"].present?
      pay_action_createWithoutResistration
    else 
      flash[:notice] = "お支払い情報が入力されていません"
      redirect_to session[:privious_url]
    end
  end
  
  # カード情報の新規登録
  def new
    @card = Card.find_by(user_id: current_user.id)
  end
  
  # クレカ情報の登録
  def create
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    if params['payjp-token'].blank?
      flash.now[:notice] = "カード情報が入力されていません。"
      render :new
    else
      begin 
        @customer = Payjp::Customer.create(
          card: params['payjp-token']
        )
        @card = Card.new(user_id: current_user.id, customer_id: @customer.id, card_id: @customer.default_card)
        @card.save
        PayMailer.mail_credit_registered(@user).deliver_now
        redirect_to user_pays_confirm_card_path
        payjp_rescue
      end
    end
  end
  
  # カード情報の確認
  def confirmCard
    @card = Card.find_by(user_id: current_user.id)
    credit_card_info
  end
  
  # カード情報の編集
  def editCard
    @card = Card.find_by(user_id: current_user.id)
    credit_card_info
  end
  
  # カード情報の更新
  def updateCard
     Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    if params['payjp-token'].blank?
      flash.now[:notice] = "カード情報が入力されていません。"
      render :editCard
    else
      begin
        @card = Card.find_by(user_id: current_user.id)
        customer = Payjp::Customer.retrieve(@card.customer_id)
        @customer = customer.cards.create(
          card: params['payjp-token'],
          default: true
        )
        @card.update(card_id: @customer.id)
        PayMailer.mail_credit_updated(@user).deliver_now
        flash[:notice] = 'クレジットカード情報が更新されました。'
        redirect_to user_pays_confirm_card_path
      rescue Payjp::CardError => e
        flash[:notice] = 'カード情報の取得ができませんでした。'
        redirect_to session[:previous_path]
      rescue Payjp::InvalidRequestError => e
        flash[:notice] = '不正なパラメータが入力されました。'
        redirect_to session[:previous_path]
      rescue Payjp::AuthenticationError => e
        flash[:notice] = 'カード情報の取得ができませんでした。'
        redirect_to session[:previous_path]
      rescue Payjp::APIConnectionError => e
        flash[:notice] = '通信エラーが発生しました。もう一度登録をしてください。'
        redirect_to session[:previous_path]
      rescue Payjp::APIError => e
        flash[:notice] = '通信エラーが発生しました。もう一度登録をしてください。'
        redirect_to session[:previous_path]
      rescue Payjp::PayjpError => e
        flash[:notice] = 'カード情報の取得ができませんでした。'
        redirect_to session[:previous_path]
      rescue StandardError
        flash[:notice] = 'エラーが発生しました。もう一度登録してください。'
        redirect_to session[:previous_path]
      end
    end
  end
  
  # 売り上げ確認
  def profit
    payjp_transfer_info
  end
  
  # イベントホストの銀行口座情報入力
  def hostNew
    @tenant = Tenant.find_by(user_id: current_user.id)
  end
  
  # イベントホストのカード情報登録
  def hostCreate
    if params[:bank_code].present? && params[:bank_branch_code].present? && params[:bank_account_type].present? &&
      params[:bank_account_number].present? && params[:bank_account_holder_name].present?  
      begin
        # payjp通信
        payjp_create_tenant
        if @tenant_id.present?
          @tenant = Tenant.new(user_id: current_user.id, tenant_id: @tenant_id)
          @tenant.save
          PayMailer.mail_bank_registered(@user).deliver_now
          flash[:notice] = "銀行口座登録が完了しました！"  
          redirect_to user_pays_hostinfo_path
        else
          flash[:notice] = "入力された銀行口座情報に誤りがあります。お手数ですがもう一度入力してください。"
          redirect_to session[:previous_path]
        end
      rescue 
        flash[:notice] = "入力した情報に不備があります。再度入力してください"    
        render :hostNew
      end
    else
    # 入力情報が空の場合
      flash[:notice] = "空欄の項目があります。すべて入力してください。"    
      render :hostNew
    end
  end
  
  # ホストが登録しているカード情報確認
  def hostInfo
    payjp_confirm_tenant
  end
  
  # ホストが登録しているカード情報の編集
  def hostEdit
    payjp_confirm_tenant
  end
  
  # ホストが登録しているカード情報の更新
  def hostUpdate
    if params[:bank_code].present? && params[:bank_branch_code].present? && params[:bank_account_type].present? &&
      params[:bank_account_number].present? && params[:bank_account_holder_name].present?  
      begin
        # payjp通信
        payjp_update_tenant
        PayMailer.mail_bank_updated(@user).deliver_now
        flash[:notice] = "口座情報を更新しました！" 
        redirect_to user_pays_hostinfo_path
      rescue 
        flash[:notice] = "入力された情報に不備があります。再度入力してください"    
        render :hostNew
      end
    else
    # 入力情報が空の場合
      flash[:notice] = "空欄の項目があります。すべて入力してください。"    
      render :hostNew
    end
  end
  
  
  
  
      private
        def pays_params
          
        end
        
        def register_bank_account
          @tenant = Tenant.find_by(user_id: current_user.id)
          unless @tenant.present?
            flash[:notice] = "銀行口座の登録を行ってください。"
            redirect_to user_pays_hostnew_path
          end
        end
        
        # 支払い情報の管理
        def pay_db_resister
          @pay = Pay.new(host_id: @event.user_id, price: @event.price, 
                         card_id: @card.id, reserve_id: @reserve.id, charge_id: @charge.id)
          @pay.user_id = current_user.id if user_signed_in?
          @pay.save
        end
        
        # カード情報の管理
        def card_db_resister
          @card = Card.new(customer_id: @customer.id, card_id: @customer.default_card)
          if @user.present?
            @card.user_id = current_user.id
          end
          @card.save
        end
        
        # payjpの支払いアクション
        def pay_action_createWithoutResistration
          begin 
            Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
            @customer = Payjp::Customer.create(
              card: params['payjp-token'],
              email: @reserve.email
            )
            card_db_resister
            @charge = Payjp::Charge.create(
              amount: @event.price.to_i,
              customer: @customer.id,
              currency: 'jpy',
              tenant: @tenant.tenant_id
            )
            pay_db_resister
            @reserve.update(payed: true)
            PayMailer.mail_pay_complite(@reserve).deliver_now
            render :createWithoutResistration
          
          rescue Payjp::CardError => e
            redirect_to pays_new_withoutresistration_path(reserve_id: @reserve.id)
            flash[:notice] = 'カード情報の取得ができませんでした。'
          rescue Payjp::InvalidRequestError => e
            redirect_to pays_new_withoutresistration_path(reserve_id: @reserve.id)
            flash[:notice] = '不正なパラメータが入力されました。'
          rescue Payjp::AuthenticationError => e
            redirect_to pays_new_withoutresistration_path(reserve_id: @reserve.id)
            flash[:notice] = 'カード情報の取得ができませんでした。'
          rescue Payjp::APIConnectionError => e
            redirect_to pays_new_withoutresistration_path(reserve_id: @reserve.id)
            flash[:notice] = '通信エラーが発生しました。もう一度登録をしてください。'
          rescue Payjp::APIError => e
            redirect_to pays_new_withoutresistration_path(reserve_id: @reserve.id)
            flash[:notice] = '通信エラーが発生しました。もう一度登録をしてください。'
          rescue Payjp::PayjpError => e
            redirect_to pays_new_withoutresistration_path(reserve_id: @reserve.id)
            flash[:notice] = 'カード情報の取得ができませんでした。'
          rescue StandardError
            redirect_to pays_new_withoutresistration_path(reserve_id: @reserve.id)
            flash[:notice] = 'エラーが発生しました。もう一度登録をしてください。'
          end
        end

        # payjpへテナント情報送信
        def payjp_create_tenant
          token = ENV["PAYJP_PRIVATE_KEY"]
          uri = URI.parse("https://api.pay.jp/v1/tenants")
          http = Net::HTTP.new(uri.host, uri.port)
          
          http.use_ssl = true
          http.verify_mode = OpenSSL::SSL::VERIFY_NONE
          req = Net::HTTP::Post.new(uri.path)
          req.basic_auth("#{token}", "")
          req.set_form_data({
            "name" => current_user.email,
            "minimum_transfer_amount" => "1000",
            "bank_account_holder_name" => params[:bank_account_holder_name],
            "bank_code" => params[:bank_code],
            "bank_branch_code" => params[:bank_branch_code],
            "bank_account_type" => params[:bank_account_type],
            "bank_account_number" => params[:bank_account_number],
            "platform_fee_rate" => "10",
            "payjp_fee_included" => true
          })
          res = http.request(req)
          data = JSON.parse(res.body)
          @tenant_id = data["id"]
        end
        
        # payjpからテナント情報取得
        def payjp_confirm_tenant
          @tenant = Tenant.find_by(user_id: current_user.id)
          if @tenant.present?
            token = ENV["PAYJP_PRIVATE_KEY"]
            uri = URI.parse("https://api.pay.jp/v1/tenants/#{@tenant.tenant_id}")

app/helpers/pays_helper.rb
module PaysHelper
end

app/views/pays/confirmCard.html.erb
<% provide(:title, "カード情報確認・変更") %>

<%= render "shared/flash" %>
<div class="container">
<div class="row">
  <div class="col-12 col-sm-3">
    <%= render "shared/sidebar_organizer" %>
  </div>
  
  <div class="col-12 col-sm-9 content">
    <div class="page-title">
      <h1>カード情報確認・変更</h1>
    </div>
    <% if @card.present? %>
    <div class="pay-form">
      <div class="pay-form__notice">
        <p>お支払いは以下に登録されたカードで行われます。</p>
      </div>
      <div class="pay-form__box-card box-wrap">
        <h2><i class="fa fa-address-book-o" aria-hidden="true"></i> 現在登録されているカード</h2>
        <table>
          <tr>
            <th>カード番号</th>
            <td>**** **** **** <%= @card_information.last4 %></td>
          </tr>
          <tr>
            <th>有効期限</th>
            <td><%= @card_information.exp_month.to_s %>/<%= @card_information.exp_year.to_s.slice(2,3) %></td>
          </tr>
          <tr>
            <th>ブランド</th>
            <td><%= @card_information.brand %></td>
          </tr>
        </table>
      </div>
      <div class="pay-form__notice">
        <p><%= link_to "登録されているカードを変更する", user_pays_edit_card_path, class:"submit-btn btn-hover orange-btn" %></p>
      </div>
    </div>
    <% else %>
    <div class="pay-form__notice">
      <p>まだカードは登録されていません。<%= link_to "カード登録", new_pay_path, data: {"turbolinks" => false}  %>よりクレジットカードを登録してください。</p>
      <p>カードを登録することで、イベントの参加がよりスムーズになります！</p>
    </div>
    <% end %>

  </div>
</div>
</div>

app/views/pays/editCard.html.erb
<% provide(:title, "お支払いカードの変更") %>

<%= render "shared/flash" %>
<div class="container">
<div class="row">
  <div class="col-12 col-sm-3">
    <%= render "shared/sidebar_organizer" %>
  </div>
  
  <div class="col-12 col-sm-9">
    <div class="page-title">
      <h1>登録カードの変更</h1>
    </div>
    
    <div class="pay-form">
      <div class="pay-form__notice">
        <p>現在登録中のカードから新しいカードへ変更できます。</p>
        <p>「カード情報を入力する」ボタンが表示されない場合は、更新ボタンを押してください。</p>
      </div>
      <div class="pay-form__box-card box-wrap">
        <h2><i class="fa fa-address-book-o" aria-hidden="true"></i> 現在登録されているカード</h2>
        <table>
          <tr>
            <th>カード番号</th>
            <td>**** **** **** <%= @card_information.last4 %></td>
          </tr>
          <tr>
            <th>有効期限</th>
            <td><%= @card_information.exp_month.to_s %>/<%= @card_information.exp_year.to_s.slice(2,3) %></td>
          </tr>
          <tr>
            <th>ブランド</th>
            <td><%= @card_information.brand %></td>
          </tr>
        </table>
      </div>
      <div class="pay-form__arrow">
        <p>&#8595;</p>
      </div>
      <div class="pay-form__box-card box-wrap">
        <p>カード情報を入力し、登録してください。</p>
        <%= form_with(url: user_pays_update_card_path, data: {remote: false}) do |f| %>
        <div>
        <script
          type="text/javascript"
          src="https://checkout.pay.jp/"
          class="payjp-button"
          data-key="<%= ENV['PAYJP_KEY'] %>"
          data-submit-text="カード情報を登録する"
          data-partial="true">
        </script>
        </div>

        <div class="pay-form__submit-box">
          <%= f.submit "支払いカードを変更する", class:"submit-btn orange-btn btn-hover", data: {"turbolinks" => false}  %>
        </div>
        <% end %>
      </div>
    </div>

  </div>
</div>
</div>

app/views/pays/hostEdit.html.erb
<% provide(:title, "口座情報変更") %>

<%= render "shared/flash" %>
<div class="container">
<div class="row">
  <div class="col-12 col-sm-3">
    <%= render "shared/sidebar_organizer" %>
  </div>
  <div class="col-12 col-sm-9 content">
    <div class="page-title">
        <h1>イベントホスト向け口座情報変更</h1>
    </div>
    <div class="pay">
      <div class="pay-form">
        <div class="pay-form__notice">
          <p>売り上げを入金するお振込口座を設定してください。</p>
        </div>
        <%= form_with(url: user_pays_hostupdate_path, data:{remote: false}) do |f| %>
          <div class="pay-form__box">
            <%= f.label:bank_code, "銀行コード" %>
            <%= f.number_field:bank_code, value: @data["bank_code"] , class:"form-control" %>
          </div>
          <div class="pay-form__box">
            <%= f.label:bank_branch_code, "支店コード" %>
            <%= f.number_field:bank_branch_code, value: @data["bank_branch_code"], class:"form-control" %>
          </div>
          <div class="pay-form__box">
            <%= f.label:bank_account_type, "預金種別" %>
            <%= f.select:bank_account_type, {'普通': "普通", '当座': "当座"}, {selected: @data["bank_account_type"]}, class:"form-control" %>
          </div>
          <div class="pay-form__box">
            <%= f.label:bank_account_number, "口座番号" %>
            <%= f.number_field:bank_account_number, value: @data["bank_account_number"], class:"form-control" %>
          </div>
          <div class="pay-form__box">
            <%= f.label:bank_account_holder_name, "口座名義" %>
            <%= f.text_field:bank_account_holder_name, value: @data["bank_account_holder_name"], class:"form-control" %>
          </div>
          <div class="pay-form__submit-box">
            <%= f.submit "変更する", class:"submit-btn orange-btn btn-hover" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>    
</div>

app/views/pays/hostInfo.html.erb
<% provide(:title, "口座情報確認") %>

<%= render "shared/flash" %>
<div class="container">
<div class="row">
  <div class="col-12 col-sm-3">
    <%= render "shared/sidebar_organizer" %>
  </div>
  <div class="col-12 col-sm-9 content">
    <div class="page-title">
        <h1>イベントホスト向け口座情報確認</h1>
    </div>
    <% if @tenant.present? %>
    <div class="pay-form__notice">
      <p>イベントにより売り上げが発生した場合、手数料10%を差し引いた売り上げが、以下登録されている口座へ振り込まれます。</p>
    </div>
    <div class="payment">
      <div class="payment-box">
        <table>
          <tr>
            <th>銀行コード</th>
            <td><%= @data["bank_code"] %></td>
          </tr>
          <tr>
            <th>支店コード</th>
            <td><%= @data["bank_branch_code"] %></td>
          </tr>
          <tr>
            <th>預金種別</th>
            <td><%= @data["bank_account_type"] %></td>
          </tr>
          <tr>
            <th>口座番号</th>
            <td><%= @data["bank_account_number"] %></td>
          </tr>
          <tr>
            <th>口座名義</th>
            <td><%= @data["bank_account_holder_name"] %></td>
          </tr>
        </table>
        <div class="payment-box__link">
          <%= link_to "振込口座を変更する", user_pays_hostedit_path, class: "submit-btn btn-hover orange-btn" %>
        </div>
      </div>
      <% else %>
      <div class="pay-form__notice">
        <p>銀行口座が登録されていません。<%= link_to "振込口座登録", user_pays_hostnew_path %>へお進みください。</p>
      </div>
    <% end %>
  </div>
        
    </div>
</div>
</div>

app/views/pays/hostNew.html.erb
<% provide(:title, "口座情報登録") %>

<%= render "shared/flash" %>
<div class="container">
<div class="row">
  <div class="col-12 col-sm-3">
    <%= render "shared/sidebar_organizer" %>
  </div>
  <div class="col-12 col-sm-9 content">
    <div class="page-title">
        <h1>イベントホスト向け口座情報登録</h1>
    </div>
    <div class="pay">
      <% if @tenant.present? %>
      <div class="pay-form__notice">
        <p>口座情報は登録されています。登録した銀行口座は<%= link_to "口座情報確認", user_pays_hostinfo_path %>から確認してください。</p>
      </div>
      <% else %>
      <div class="pay-form">
        <div class="pay-form__notice">
          <p>売り上げを入金する銀行口座を設定してください。</p>
        </div>
        <%= form_with(url: user_pays_host_path, data:{remote: false}) do |f| %>
          <div class="pay-form__box">
            <%= f.label:bank_code, "銀行コード" %>
            <%= f.number_field:bank_code, class:"form-control" %>
          </div>
          <div class="pay-form__box">
            <%= f.label:bank_branch_code, "支店コード" %>
            <%= f.number_field:bank_branch_code, class:"form-control" %>
          </div>
          <div class="pay-form__box">
            <%= f.label:bank_account_type, "預金種別" %>
            <%= f.select:bank_account_type, {'普通': "普通", '当座': "当座"}, {}, class:"form-control" %>
          </div>
          <div class="pay-form__box">
            <%= f.label:bank_account_number, "口座番号" %>
            <%= f.number_field:bank_account_number, class:"form-control" %>
          </div>
          <div class="pay-form__box">
            <%= f.label:bank_account_holder_name, "口座名義" %>
            <%= f.text_field:bank_account_holder_name, class:"form-control" %>
          </div>
          <div class="pay-form__submit-box">
            <%= f.submit "登録する", class:"submit-btn orange-btn btn-hover" %>
          </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>    
</div>

app/views/pays/new.html.erb
<% provide(:title, "お支払いカードの登録") %>

<%= render "shared/flash" %>
<div class="container">
<div class="row">
  <div class="col-12 col-sm-3">
    <%= render "shared/sidebar_organizer" %>
  </div>
  
  <div class="col-12 col-sm-9 content">
    <div class="page-title">
      <h1>お支払いカード登録</h1>
    </div>
    <% if @card.present? %>
    <div class="pay-form">
      <div class="pay-form__notice">
        <p>カード情報はすでに登録されています。登録されているカードの変更を行う場合は、「<%= link_to "カード確認・変更", user_pays_confirm_card_path %> 」よりお進みください。</p>
      </div>
    </div>
    <% else %>
    <div class="pay-form">
      <div class="pay-form__notice">
        <p>カードを登録することで、イベント予約と同時にお支払いが完了します。</p>
        <p>「カード情報を入力する」ボタンが表示されない場合は、更新ボタンを押してください。</p>
      </div>
      <div class="pay-form__box-card box-wrap">
        <p>カード情報を入力し、登録してください。</p>
        <%= form_with(url: pays_path, data: {remote: false}) do |f| %>
        <script
          type="text/javascript"
          src="https://checkout.pay.jp/"
          class="payjp-button"
          data-key="<%= ENV['PAYJP_KEY'] %>"
          data-submit-text="カード情報を登録する"
          data-partial="true">
        </script>

        <div class="pay-form__submit-box">
          <%= f.submit "登録する", class:"submit-btn orange-btn btn-hover"  %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>

app/views/pays/newWithoutResistration.html.erb
<% provide(:title, "お支払い") %>

<%= render "shared/flash" %>
<div class="container">
<div class="row">
  <div class="payment">
    <div class="page-title">
      <h1>お支払い</h1>
    </div>
    <div class="payment-box">
    <% if @reserve.payed %>
      <p class="wide-submit-btn pink-btn">すでに参加費は支払い済みです！</p>
    <% elsif to_date_and_time(@event.start_date, @event.start_time) <= Time.zone.now.to_date &&  %>
      <p class="wide-submit-btn pink-btn">イベント開催日時がすでに過ぎています。</p>
    <% else %>
      <p>お支払いいただくことで、参加登録が完了します。表示された情報に間違いがないことをご確認いただき、お支払いをお願いします。</p>
      <% unless @reserve.present? %>
      <p class="wide-submit-btn pink-btn">イベント情報の取得が正常にできておりません。誠に恐れ入りますが、再度ご予約いただくか運営までご連絡ください。</p>
      <% end %>
    <% end %>
    </div>
    <div class="payment-box">
      <h2><i class="fa fa-user" aria-hidden="true"></i> お客様の情報</h2>
      <table>
        <tr>
          <th>ニックネーム</th>
          <td><%= @reserve.nickname if @reserve.present? %></td>
        </tr>
        <tr>
          <th>E-mail</th>
          <% if @reserve.present? %>
          <% @size = @reserve.email.size.to_i - 2 %>
          <td><%= @reserve.email[0, 2] %><%= "*"*@size %></td>
          <% end %>
        </tr>
      </table>  
    </div>
    <div class="payment-box">
      <h2><i class="fa fa-bookmark-o" aria-hidden="true"></i> 予約したイベント</h2>
      <table>
        <tr>
          <th>イベント名</th>
          <td><%= @event.title if @event.present? %></td>
        </tr>
        <tr>
          <th>開催日時</th>
          <td><%= @event.start_date.strftime("%Y年%m月%d日") if @event.present? %> <%= @event.start_time.strftime("%H:%M～") if @event.present? %></td>
        </tr>
        <tr>
          <th>費用</th>
          <td><%= @event.price.to_s(:delimited) if @event.present? %> 円</td>
        </tr>
        <tr>
          <th>定員</th>
          <td><%= @event.capacity if @event.present? %> 名</td>
        </tr>
        <tr>
          <th>主催者</th>
          <td><%= User.find(@event.user_id).nickname if @event.present? %></td>
        </tr>
      </table>
    </div>
    <% unless @reserve.payed || to_date_and_time(@event.start_date, @event.start_time) <= Time.zone.now.to_date %>
    <div class="payment-box">
      <h2><i class="fa fa-credit-card" aria-hidden="true"></i> カード情報の登録</h2>
      <p>有効なカード情報の入力を行ってください。</p>
      <%= form_with(url: pays_create_withoutresistration_path, data: {remote: false}) do |f| %>
      <%= f.hidden_field:reserve_id, value: @reserve.id  if @reserve.present? %>
      <script
        type="text/javascript"
        src="https://checkout.pay.jp/"
        class="payjp-button"
        data-key="<%= ENV["PAYJP_KEY"] %>"
        data-submit-text="カードを登録する"
        data-partial="true">
      </script>
      <div class="payment-box__submit">
        <p><%= link_to "利用規約", term_path, style:"font-weight: bold;" %>、<%= link_to "プライバシーポリシー", privacy_path, style:"font-weight: bold;" %>に同意の上 </p>
        <%= f.submit "支払いする", class: "orange-btn wide-submit-btn btn-hover" %>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
  
</div>  
</div>