config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "events#top"
  get "/contact",   to: "static_page#contact"
  post "/contact",  to: "static_page#contact_for_admin"
  
  #特定商取引法に基づく表記
  get "/tokushohyo",  to: "static_page#tokushohyo"
  get "/term",        to: "static_page#term"
  get "/privacy",     to: "static_page#privacy"
  get "/howtouse",     to: "static_page#howtouse"
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
#    :confirmations => 'users/confirmations'
  }
  
#   ユーザー管理関連
  resources :users, only: [:show]

  
# イベント管理関連  
  get "events/confirm", to: "events#confirm"
  resources :events do
    resources :reserves,     only: [:create]
    post "/create_with_resistration", to: "reserves#createWithResistration" 
  end
  resources :reserves,       only: [:destroy]
  get "reserves/:id/cancel", to: "reserves#cancel"
  get "user/reserved",       to: "reserves#reserved"
  
  
# ユーザー情報関連
  get "user/profile",       to: "users#profile"
  get "user/edit",          to: "users#edit"
  patch "user/update",      to: "users#update"
  patch "user/update_pass", to: "users#updatePass"
  post "passwords",         to: "users#resetPass"

# 支払い関連
  resources :pays, only: [:new, :create]
  get "user/pays/confirm_card",           to: "pays#confirmCard"
  get "user/pays/edit_card",              to: "pays#editCard"
  post "user/pays/update_card",           to: "pays#updateCard"
  get "user/pays/confirm",                to: "pays#confirm"
  get "user/pays/hostnew",                to: "pays#hostNew"
  post "user/pays/host"  ,                to: "pays#hostCreate"
  get "user/pays/hostinfo" ,              to: "pays#hostInfo"
  get "user/pays/hostedit",               to: "pays#hostEdit"
  post "user/pays/hostupdate",            to: "pays#hostUpdate"
  get "pays/new_withoutresistration",     to: "pays#newWithoutResistration"
  post "pays/create_withoutresistration", to: "pays#createWithoutResistration"
  get "user/pays/profit",                 to: "pays#profit"
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <nav>
    <ul>
      <li><%= link_to "ホーム", root_path %></li>
      <% unless user_signed_in? %>
      <li><%= link_to "新規ユーザー登録", new_user_registration_path %></li>
      <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
      <li><%= link_to "使い方", howtouse_path %></li>
      <li><%= link_to "問い合わせ", contact_path %></li>
      <li><%= link_to "特定商取引法に基づく表記", tokushohyo_path %></li>
      <li><%= link_to "プライバシーポリシー", privacy_path %></li>
      <li><%= link_to "利用規約", term_path %></li>
      <li></li>
    </ul>
  </nav>  
  <div class="footer-copyright">
    <p>Copyright ©2020 Realtime Social All Right Reserved. </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="header-logo">
   <h2><%= link_to "Realtime Social", root_path %> </a></h2>
  </div>
  <div class="header-link">
    <nav>
      <ul>
      <% if user_signed_in? %>
        <li class="ham btn-hover">
          <span class="ham-top"></span>
          <span class="ham-mid"></span>
          <span class="ham-bot"></span>
        </li>
        <li id="ham"></li>
        
      <% else %>
        <li class="ham btn-hover mobile-menu">
          <span class="ham-top"></span>
          <span class="ham-mid"></span>
          <span class="ham-bot"></span>
        </li>
        <li id="ham" class="mobile-menu"></li>
        <li class="pc-menu"><%= link_to "ログイン", new_user_session_path %></li>
        <li class="pc-menu"><%= link_to "新規登録", new_user_registration_path %></li>
      <% end %>
      </ul>
    </nav>
  </div>
</div>




<script>
$(function(){
  var menu = `
    <div class="header-menu" id="header-menu">
      <p class="btn-hover" id="menu-close">&times;</p>
      <% if user_signed_in? %>
      <li><i class="fa fa-home" aria-hidden="true"></i> <%= link_to "ホーム", root_path %></li>
      <li><i class="fa fa-user" aria-hidden="true"></i> <%= link_to "マイページ", user_profile_path %></li>
      <li><i class="fa fa-thumb-tack" aria-hidden="true"></i> <%= link_to "イベント作成", new_event_path %></li>
      <li><i class="fa fa-sign-out" aria-hidden="true"></i> <%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li class=""><%= link_to "ログイン", new_user_session_path %></li>
      <li class=""><%= link_to "新規登録", new_user_registration_path %></li>
      <% end %>
    </div>`
  
  function menuClose(){
    $("#menu-close").on("click", function(){
      $.when(
        $("#header-menu").animate({
          'marginRight': '-30rem'
        }),
        $("#display").animate({
          'opacity': '0'
        })
      ).done(function(){
        $("#display").css("display", "none");
        $("#header-menu").remove(); 
      });
    });
  }
  
  menuClose();
  // ヘッダーメニューを表示
  $(".ham").on("click", function(){
    $.when(
      $("#display").css("display", ""),
      $("#ham").append(menu)  
    ).done(function(){
      $("#header-menu").animate({
        'marginRight': '30rem'
      });
      $("#display").animate({
        'opacity': '.8'
      });
      
      // メニューを閉じる
      menuClose();
    });
  });  
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--動的タイトル・メタディスクリプション-->
    <title><%= full_title(yield(:title)) %></title>
    <meta name="discription" content="<%= meta_discription(yield(:content)) %>">
    <!--logo フォント	-->
    <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
    <!--assets-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--slickプラグイン-->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <meta name="viewport" content="width=device-width">
    <!--ファビコン-->
    <%= favicon_link_tag('favicon.png') %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "shared/flash" %>
    <div class="main">
      <%= yield %>
      <div id="display" style="display:none; opacity:0;"></div>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>